import Head from 'next/head'
import Image from 'next/image'
import Navbar from './components/navbar'
import styles from '../styles/Home.module.css'

export default function Home({children}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Learn Next Js Abad</title>
        <meta name="description" content="Generated by create next app initial-scale=1.0, width=device-width" key="viewport" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <main>{children}</main>
      </main>

      {/* <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Next.js 
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="blog" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <div className={styles.card}>
            <Link href="blog">
              Learning Blog &rarr;
            </Link>
            
          </div>
        </div>
      </main> */}

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
